### ISSUE TITLE
Screen becomes strange display when it runs on LXTerminal

### ISSUE THREAD

**Issue by tSU-RooT** [k0kubun/tetris#2]
I tried to play your tetris on my LXTerminal, but it didn't run correctly.
Please see below;
![tetris-output](https://cloud.githubusercontent.com/assets/1822861/12721987/ebaf5afa-c945-11e5-84f0-bc6335ee3b05.gif)

I updated library(k0kubun/termbox-go) to latest version(nsf/termbox-go), but nonetheless screen was strange on LXTerminal.

However, I tested this program on other terminal(XTerm, UXTerm, iTerm on Mac, xfce4-terminal on Xubuntu),I couldn't find same behavior.

Do you have any idea about this problem?
If not, Would I report this problem to library's upstream(nsf/termbox-go)?

```
My Environment Info:
$ uname -a
Linux tsr-X205TA 4.1.0-040100-generic #201510261105 SMP Mon Oct 26 11:08:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ go version
go version go1.5.3 linux/amd64

OS:Lubuntu 15.10
Desktop:LXDE
Terminal:LXTerminal 0.2.0
```

**Comment by k0kubun** [comment]
Indeed, it's reproductive. And it didn't happen when I changed block's character to some simple ASCII character, such as 'a'. Maybe it's a problem of treating such a fragile character used for a block in LXTerminal.

**Comment by tSU-RooT** [comment]
Thanks for your reply.

Hmm..., Do you think that this problem is caused by processing of LXTerminal?
I am using LXTerminal for developing CLI application which is using termbox-go library.

**Comment by k0kubun** [comment]
> Hmm..., Do you think that this problem is caused by processing of LXTerminal?

I think so because this isn't reproductive in xterm and urxvt.

As I said in https://github.com/k0kubun/tetris/issues/2#issuecomment-178047711, I think you may not need to mind about this problem if you don't use some special characters that tetris uses for blocks.

**Comment by tSU-RooT** [comment]
I understood, I will avoid using some special characters.
Such as "▓"

Thank you.
